### PR TITLE
Basic structure for development of OpenAPI parser

### PR DESCRIPTION
**Pull request by de-sh**
Contains only files necessary to build an OpenAPI parser moved from within hydrus.
NOTE: Hydrus is not included in requirements.txt. Should it be?

### CODE REVIEW

**Comment by chrizandr** [comment]
Since imports are from hydrus it should be added to the requirements

**Comment by de-sh** [comment]
Ok, up to it! @chrizandr should I also add the tests from hydrus/tests/test_parser.py?

**Comment by xadahiya** [comment]
hydrus CLI and a couple of other files need the parser as a dependency and parser needs hydrus as a dependency. If we create separate  packages won't it create circular dependency error?

**Comment by de-sh** [comment]
> won't it create circular dependency error?

Yeah, a mono repo is more obviously better here... but, don't take my word for it...

**Comment by chrizandr** [comment]
Not sure what you mean by a mono repo.

Since we are only using `doc_writer` from hydrus, maybe create a copy of the `doc_writer` here?

**Comment by xadahiya** [comment]
What about DRY principal then?

**Comment by de-sh** [comment]
> Not sure what you mean by a mono repo.

Big repos that contain all necessary components within it, making code DRY, but extremely large bundles...
https://en.wikipedia.org/wiki/Monorepo

**Comment by chrizandr** [comment]
> > Not sure what you mean by a mono repo.
> 
> Big repos that all necessary components within it, making code DRY, but extremely large bundles...
> https://en.wikipedia.org/wiki/Monorepo

Okay. I don't think it's not a good idea to bundle them in one repo. The parser is still in the early stages, a lot is left to be added to it. A lot more work will be done and it will have use cases where hydrus is not needed. 

> What about DRY principal then?

Agreed that this will be violated. Maybe consider moving the `hydraspec` module out of `hydrus`. Since they are mostly tools that can be used even without `hydrus`.

We might need more discussion on this.

**Comment by shravandoda** [comment]
Was anyone able to solve the issue without making the PyPi package?
I couldn't find a way to do it with github. Pip cannot install egg files

**Comment by de-sh** [comment]
Yeah, I used a similar trick as yours, but I used [this file](https://github.com/HTTP-APIs/python-hydra-agent/blob/master/.travis.yml) by @xadahiya as inspiration 😃

It needs to be a chnage in the CI config file.

**Comment by Mec-iS** [comment]
I suppose we should re-organize the code so that hydrus can use the parser as an external library.
Segregation of concerns is evidently not in place if there is so much entanglement between hydrus and the parser.

I have opened #5 as reference issue.

**Comment by shravandoda** [comment]
> Yeah, I used a similar trick as yours, but I used [this file](https://github.com/HTTP-APIs/python-hydra-agent/blob/master/.travis.yml) by @xadahiya as inspiration 
> 
> It needs to be a chnage in the CI config file.

Nice!

**Comment by chrizandr** [comment]
I've opened a develop branch in the repo, please create all PRs to develop.

**Comment by de-sh** [comment]
I guess we can reopen this for further discussion as this is now in develop base...

**Comment by Mec-iS** [comment]
as per `hydra-python-core`, this repository has to preserve the history of commits from `hydrus`

**Comment by Mec-iS** [comment]
> Contains only files necessary to build an OpenAPI parser moved from within hydrus.
NOTE: Hydrus is not included in requirements.txt. Should it be?

Only `hydrus` should import `hydra-openapi-parser`. In no way the parser should import from hydrus.
The parser should have its own CLI, called from `hydrus` when it is available, otherwise the parser should be usable also with its own CLI.

**Comment by de-sh** [comment]
@Mec-iS Almost done here, would be wonderful if you could point out how to refactor 
```
abs_path = os.path.abspath("{}/samples/petstore_openapi.yaml".format(os.path.dirname(
        hydrus.__file__)))
``` 
within test_parser.py

**Comment by de-sh** [comment]
How must I refactor the test_parser.py to reflect that the absolute path is not from a hydrus module but the openapi_parser module?

**Comment by Mec-iS** [comment]
Use `os.path.dir` to find the right directory from the module's starting directory (you can use `abs(__file__)`).

**Comment by de-sh** [comment]
I had some issues with `Module not found: hydra-openapi-parser` but I solved by instead using `__file__../` effectively redirecting to the parent directory, as was required to be done.

**Comment by Mec-iS** [comment]
@de-sh Please open a new PR on the newly imported code at df27d3016e218734b0df4fbaadc26390e753b0b0

**Pull request closed without merging**
